import type { Listing } from "./types";

/**
 * Seed parity with the demo site's 8 homes (Stays.html PROPS array),
 * enriched with the fields the real schema carries. Replaced by the
 * Supabase repository once the project is connected.
 */
const MOCK_FEATURED = new Set(["spiritum-marea", "vista-playa", "casa-selva", "nile-breeze"]);

const RAW: Omit<Listing, "featured" | "instantBook" | "selfCheckIn" | "allowPets">[] = [
  {
    id: "l-spiritum-marea",
    slug: "spiritum-marea",
    title: "Spiritum Marea",
    city: "Playa del Carmen",
    country: "MX",
    region: "Riviera Maya",
    lat: 20.654,
    lng: -87.068,
    propertyType: "condo",
    maxGuests: 6,
    bedrooms: 2,
    bathrooms: 2,
    headline: "Oceanfront",
    description:
      "A bright oceanfront walkout in the gated Mareazul community, steps from a white-sand beach and three lagoon-style pools. Floor-to-ceiling windows open onto a private terrace with direct garden-to-beach access.",
    amenities: ["Beachfront access", "Lagoon pools", "Full kitchen", "Air conditioning", "Fast Wi-Fi", "Washer", "Free parking", "WhatsApp concierge"],
    minStay: 3,
    rating: 4.94,
    reviewCount: 128,
    photos: [],
    gradient: "ph-g1",
    nightlyCents: 16000,
    cleaningCents: 6000,
    taxPct: 16,
    currency: "USD",
  },
  {
    id: "l-vista-playa",
    slug: "vista-playa",
    title: "Vista Playa",
    city: "Playa del Carmen",
    country: "MX",
    region: "Riviera Maya",
    lat: 20.6296,
    lng: -87.0739,
    propertyType: "penthouse",
    maxGuests: 8,
    bedrooms: 3,
    bathrooms: 3,
    headline: "Penthouse",
    description:
      "A rooftop penthouse with a private plunge pool and sweeping Caribbean views, two blocks from Quinta Avenida's restaurants and nightlife.",
    amenities: ["Rooftop pool", "Ocean view", "Full kitchen", "Air conditioning", "Fast Wi-Fi", "Elevator", "WhatsApp concierge"],
    minStay: 3,
    rating: 4.87,
    reviewCount: 96,
    photos: [],
    gradient: "ph-g2",
    nightlyCents: 20000,
    cleaningCents: 7500,
    taxPct: 16,
    currency: "USD",
  },
  {
    id: "l-casa-selva",
    slug: "casa-selva",
    title: "Casa Selva",
    city: "Tulum",
    country: "MX",
    region: "Riviera Maya",
    lat: 20.2114,
    lng: -87.4654,
    propertyType: "villa",
    maxGuests: 10,
    bedrooms: 4,
    bathrooms: 4,
    headline: "Jungle villa",
    description:
      "A private jungle villa in Aldea Zamá with a 12-metre pool, outdoor kitchen and palapa lounge — five minutes from Tulum beach.",
    amenities: ["Private pool", "Garden", "Outdoor kitchen", "Air conditioning", "Fast Wi-Fi", "Free parking", "Family friendly", "WhatsApp concierge"],
    minStay: 4,
    rating: 4.91,
    reviewCount: 74,
    photos: [],
    gradient: "ph-g3",
    nightlyCents: 32000,
    cleaningCents: 9000,
    taxPct: 16,
    currency: "USD",
  },
  {
    id: "l-nile-breeze",
    slug: "nile-breeze",
    title: "Nile Breeze",
    city: "Nuba",
    country: "EG",
    region: "Upper Egypt",
    lat: 24.0889,
    lng: 32.8998,
    propertyType: "house",
    maxGuests: 8,
    bedrooms: 3,
    bathrooms: 2,
    headline: "Family",
    description:
      "A Nubian guesthouse on the banks of the Nile with a shaded roof terrace, home-cooked breakfast and felucca trips at sunset.",
    amenities: ["Nile view", "Roof terrace", "Breakfast included", "Air conditioning", "Wi-Fi", "Family friendly", "WhatsApp concierge"],
    minStay: 2,
    rating: 4.96,
    reviewCount: 63,
    photos: [],
    gradient: "ph-g4",
    nightlyCents: 11000,
    cleaningCents: 3000,
    taxPct: 14,
    currency: "USD",
  },
  {
    id: "l-palma-azul",
    slug: "palma-azul",
    title: "Palma Azul",
    city: "Playa del Carmen",
    country: "MX",
    region: "Riviera Maya",
    lat: 20.63,
    lng: -87.08,
    propertyType: "condo",
    maxGuests: 5,
    bedrooms: 2,
    bathrooms: 2,
    headline: "Private pool",
    description:
      "A calm garden condo with its own plunge pool in a palm-shaded residencial, a short bike ride from the beach clubs.",
    amenities: ["Private pool", "Garden", "Full kitchen", "Air conditioning", "Fast Wi-Fi", "Family friendly", "WhatsApp concierge"],
    minStay: 2,
    rating: 4.9,
    reviewCount: 58,
    photos: [],
    gradient: "ph-g2",
    nightlyCents: 14500,
    cleaningCents: 5000,
    taxPct: 16,
    currency: "USD",
  },
  {
    id: "l-coral-suite",
    slug: "coral-suite",
    title: "Coral Suite",
    city: "Playa del Carmen",
    country: "MX",
    region: "Riviera Maya",
    lat: 20.625,
    lng: -87.07,
    propertyType: "condo",
    maxGuests: 3,
    bedrooms: 1,
    bathrooms: 1,
    headline: "Beachfront",
    description:
      "A cosy beachfront suite for couples — wake to the sound of the waves, coffee on the balcony, toes in the sand in sixty seconds.",
    amenities: ["Beachfront access", "Balcony", "Kitchenette", "Air conditioning", "Fast Wi-Fi", "WhatsApp concierge"],
    minStay: 2,
    rating: 4.85,
    reviewCount: 87,
    photos: [],
    gradient: "ph-g1",
    nightlyCents: 12000,
    cleaningCents: 4000,
    taxPct: 16,
    currency: "USD",
  },
  {
    id: "l-villa-maya",
    slug: "villa-maya",
    title: "Villa Maya",
    city: "Tulum",
    country: "MX",
    region: "Riviera Maya",
    lat: 20.2,
    lng: -87.47,
    propertyType: "villa",
    maxGuests: 12,
    bedrooms: 5,
    bathrooms: 5,
    headline: "Villa",
    description:
      "Our flagship five-bedroom estate: chef's kitchen, heated pool, cinema room and staff quarters — built for celebrations and big family escapes.",
    amenities: ["Private pool", "Chef's kitchen", "Cinema room", "Garden", "Air conditioning", "Fast Wi-Fi", "Free parking", "WhatsApp concierge"],
    minStay: 4,
    rating: 4.98,
    reviewCount: 41,
    photos: [],
    gradient: "ph-g4",
    nightlyCents: 41000,
    cleaningCents: 12000,
    taxPct: 16,
    currency: "USD",
  },
  {
    id: "l-casa-sol",
    slug: "casa-sol",
    title: "Casa Sol",
    city: "Orlando",
    country: "US",
    region: "Florida",
    lat: 28.3852,
    lng: -81.5639,
    propertyType: "house",
    maxGuests: 10,
    bedrooms: 4,
    bathrooms: 3,
    headline: "Near parks",
    description:
      "A sunny four-bedroom home ten minutes from the Disney gates, with a screened pool, game room and space for the whole crew.",
    amenities: ["Private pool", "Game room", "Full kitchen", "Air conditioning", "Fast Wi-Fi", "Free parking", "Family friendly", "WhatsApp concierge"],
    minStay: 3,
    rating: 4.88,
    reviewCount: 69,
    photos: [],
    gradient: "ph-g3",
    nightlyCents: 18000,
    cleaningCents: 8000,
    taxPct: 12.5,
    currency: "USD",
  },
  {
    id: "l-jardin-verde",
    slug: "jardin-verde",
    title: "Jardin Verde",
    city: "Playa del Carmen",
    country: "MX",
    region: "Riviera Maya",
    lat: 20.632,
    lng: -87.076,
    propertyType: "condo",
    maxGuests: 7,
    bedrooms: 3,
    bathrooms: 2,
    headline: "Garden",
    description:
      "A leafy three-bedroom condo built around a green courtyard and pool, a short stroll from the beach and Fifth Avenue. Bright, spacious and quiet \u2014 a comfortable home base for families and groups.",
    amenities: ["Courtyard pool", "Garden", "Full kitchen", "Air conditioning", "Wi-Fi", "Free parking", "Washer", "Smart TV", "Walk to beach", "24/7 concierge"],
    minStay: 2,
    rating: 4.83,
    reviewCount: 71,
    photos: [],
    gradient: "ph-g3",
    nightlyCents: 17500,
    cleaningCents: 6000,
    taxPct: 16,
    currency: "USD",
  },
];

export const MOCK_LISTINGS: Listing[] = RAW.map((l) => ({
  ...l,
  featured: MOCK_FEATURED.has(l.slug),
  instantBook: true,
  selfCheckIn: false,
  allowPets: false,
}));

/** demo parity: bookable via direct link, hidden from the grid */
export const UNLISTED_SLUGS = new Set(["jardin-verde"]);
