-- Amanah Vacations catalog seed: 9 tours + 6 parks (demo parity).
-- Prices in MXN cents per person. Idempotent via slug upsert.

insert into public.tours
  (slug, title, subtitle, partner, city, duration_hours, duration_label,
   description, highlights, price_cents, currency, min_group, max_group,
   category, status)
values
  ('cenotes-coral-sea-turtles','Cenotes, Coral & Sea Turtles','Dos Ojos Cenote + Akumal Snorkeling','amanah','Playa del Carmen',6,'6 hours',
   'Swim through the sacred chambers of Cenote Dos Ojos, then snorkel alongside sea turtles in Akumal Bay.',
   array['Cenote Dos Ojos swim','Sea turtle snorkeling','Private A/C van','Akumal beach time'],235000,'MXN',1,6,'tour','published'),
  ('cenotes-ruins-tulum','Cenotes & the Ruins of Tulum','Dos Ojos Cenote + Tulum Site','amanah','Playa del Carmen',7,'6–8 hours',
   'A private guided tour of the only Maya city built on the coast, plus a swim in Cenote Dos Ojos.',
   array['Tulum clifftop ruins','Cenote Dos Ojos swim','Private guide','Playa Ruinas'],370000,'MXN',1,6,'tour','published'),
  ('coba-ruins-jungle-cenotes','Cobá Ruins & Jungle Cenotes','Coba Zone + Choo-Ha & Tankach-Ha','amanah','Playa del Carmen',9,'Full day',
   'Climb into the jungle to Nohoch Mul, the tallest pyramid on the Yucatán Peninsula, then cool off in two hidden cenotes.',
   array['Nohoch Mul pyramid','Two jungle cenotes','Private guide'],390000,'MXN',1,6,'tour','published'),
  ('cozumel-private-boat','Cozumel Private Boat Snorkeling','El Cielo, Colombia & Lever Reefs','amanah','Cozumel',4,'Approx. 4 hours',
   'A private boat to four of Cozumel''s best reefs, with fresh ceviche and drinks on board.',
   array['4 reef stops','Private boat','Ceviche & drinks aboard'],460000,'MXN',1,6,'tour','published'),
  ('tulum-akumal','Tulum & Akumal','Dos Ojos + Tulum Ruins + Akumal','amanah','Playa del Carmen',9,'Full day',
   'The best of both worlds — ancient ruins, a sacred cenote and sea turtles in one action-packed day.',
   array['Tulum ruins','Cenote Dos Ojos','Akumal turtles'],585000,'MXN',1,6,'tour','published'),
  ('chichen-itza-valladolid','Chichen Itza & Valladolid','New 7 Wonders + Suytun & Samulá','amanah','Playa del Carmen',11,'Full day',
   'A wonder of the world, a colonial pueblo mágico, and two of the Yucatán''s most beautiful cenotes.',
   array['Chichén Itzá guided tour','Valladolid','Cenote Suytun','Cenote Samulá'],660000,'MXN',1,6,'tour','published'),
  ('ruta-de-cenotes','Ruta de Cenotes','4 Cenotes + Diving Platform + Zip Line','amanah','Puerto Morelos',5,'Half day',
   'Two open-air and two underground cenotes, a diving platform and a water zip line in one jungle park.',
   array['4 cenotes','Diving platform','Water zip line'],290000,'MXN',1,6,'tour','published'),
  ('holbox-island-escape','Holbox Island Escape','2 Days, 1 Night','amanah','Holbox',24,'Overnight',
   'A car-free island of flamingos, bioluminescent water and untouched beaches. Arranged personally with you.',
   array['Flamingos & bioluminescence','Overnight stay'],0,'MXN',1,6,'tour','draft'),
  ('isla-contoy','Isla Contoy National Park','Ixlaché Reef + Contoy + Isla Mujeres','amanah','Cancún',10,'Full day',
   'A protected bird sanctuary limited to 200 visitors a day — the wildest corner of the Mexican Caribbean.',
   array['Protected sanctuary','Reef snorkeling','Isla Mujeres'],0,'MXN',1,6,'tour','draft'),
  ('xcaret-park','Xcaret Park','Eco-archaeological park + night show','amanah','Playa del Carmen',12,'All-day access',
   'Mexico''s iconic eco-park — underground rivers, wildlife encounters and the legendary Xcaret México Espectacular night show.',
   array['Underground rivers','Night show','Wildlife'],350000,'MXN',1,12,'park','published'),
  ('xel-ha-park','Xel-Há Park','All-inclusive natural aquarium','amanah','Tulum',10,'All-day access',
   'Snorkel paradise in a natural inlet — lazy river, cliff of courage, and unlimited food & drinks all day.',
   array['Snorkeling inlet','Unlimited food & drinks','Lazy river'],285000,'MXN',1,12,'park','published'),
  ('xplor-park','Xplor Park','Zip-lines + caverns + amphibious vehicles','amanah','Playa del Carmen',10,'All-day access',
   'Adrenaline underground: soar the jungle on zip-lines, drive amphibious vehicles and paddle rafts through stalactite caverns.',
   array['Zip-lines','Underground rafting','Amphibious vehicles'],335000,'MXN',1,12,'park','published'),
  ('xplor-fuego-park','Xplor Fuego Park','The night version, lit by fire','amanah','Playa del Carmen',5,'Evening access',
   'Xplor after dark — the same caves and zip-lines transformed by firelight. A completely different adventure.',
   array['Night zip-lines','Firelit caverns'],285000,'MXN',1,12,'park','published'),
  ('xenses-park','Xenses Park','Half-day park of the senses','amanah','Playa del Carmen',5,'Half-day access',
   'A park that plays with your mind — optical illusions, a town where nothing is what it seems, and rivers of salt water and mud.',
   array['Optical illusions','Salt river','Mud river'],185000,'MXN',1,12,'park','published'),
  ('jungala-aqua-park','Jungala Aqua Park','Waterpark in the jungle','amanah','Playa del Carmen',8,'All-day access',
   'The Riviera''s great waterpark — wave river, giant slides and jungle cabanas for the whole family.',
   array['Wave river','Giant slides','Cabanas'],180000,'MXN',1,12,'park','published')
on conflict (slug) do update set
  title=excluded.title, subtitle=excluded.subtitle, city=excluded.city,
  duration_hours=excluded.duration_hours, duration_label=excluded.duration_label,
  description=excluded.description, highlights=excluded.highlights,
  price_cents=excluded.price_cents, currency=excluded.currency,
  min_group=excluded.min_group, max_group=excluded.max_group,
  category=excluded.category, status=excluded.status;
